export interface Deal {
  id: string
  company: string
  contact: string
  stage: string
  value: number
  repName: string
  lastActivity: string
  probability: number
  daysInStage: number
  createdAt: string
}

export const pipelineStages = [
  'lead',
  'discovery',
  'demo',
  'proposal',
  'negotiation',
  'closed-won',
  'closed-lost',
] as const

export const mockDeals: Deal[] = [
  {
    id: 'deal-1',
    company: 'Acme Corp',
    contact: 'Alex Rivera',
    stage: 'discovery',
    value: 48000,
    repName: 'Sarah Chen',
    lastActivity: 'Discovery call — positive sentiment',
    probability: 20,
    daysInStage: 2,
    createdAt: '2026-05-27T09:00:00Z',
  },
  {
    id: 'deal-2',
    company: 'Vertex Labs',
    contact: 'Jordan Lee',
    stage: 'demo',
    value: 120000,
    repName: 'Marcus Johnson',
    lastActivity: 'Budget objection surfaced — ROI calculator sent',
    probability: 40,
    daysInStage: 5,
    createdAt: '2026-05-26T14:30:00Z',
  },
  {
    id: 'deal-3',
    company: 'Nebula Systems',
    contact: 'Priya Sharma',
    stage: 'proposal',
    value: 85000,
    repName: 'Sarah Chen',
    lastActivity: 'Legal reviewing DPA',
    probability: 70,
    daysInStage: 8,
    createdAt: '2026-05-25T11:00:00Z',
  },
  {
    id: 'deal-4',
    company: 'Orbital Data',
    contact: 'Rachel Kim',
    stage: 'negotiation',
    value: 210000,
    repName: 'David Park',
    lastActivity: 'Security review pending SOC 2',
    probability: 60,
    daysInStage: 12,
    createdAt: '2026-05-24T16:00:00Z',
  },
  {
    id: 'deal-5',
    company: 'Pulse Health',
    contact: 'Chris Morgan',
    stage: 'discovery',
    value: 65000,
    repName: 'Aisha Patel',
    lastActivity: 'Positioning as Gong complement',
    probability: 15,
    daysInStage: 1,
    createdAt: '2026-05-23T10:00:00Z',
  },
  {
    id: 'deal-6',
    company: 'Kinetic AI',
    contact: 'Ryan Torres',
    stage: 'closed-won',
    value: 156000,
    repName: 'Marcus Johnson',
    lastActivity: 'Kickoff scheduled June 2',
    probability: 100,
    daysInStage: 0,
    createdAt: '2026-05-22T13:00:00Z',
  },
  {
    id: 'deal-7',
    company: 'Stark Industries',
    contact: 'Tony Stark',
    stage: 'lead',
    value: 95000,
    repName: 'Sarah Chen',
    lastActivity: 'Inbound from website demo request',
    probability: 10,
    daysInStage: 1,
    createdAt: '2026-05-28T08:00:00Z',
  },
  {
    id: 'deal-8',
    company: 'Wayne Enterprises',
    contact: 'Bruce Wayne',
    stage: 'demo',
    value: 180000,
    repName: 'David Park',
    lastActivity: 'Security requirements discussion',
    probability: 45,
    daysInStage: 6,
    createdAt: '2026-05-20T11:00:00Z',
  },
  {
    id: 'deal-9',
    company: 'Cyberdyne Systems',
    contact: 'Sarah Connor',
    stage: 'closed-lost',
    value: 75000,
    repName: 'Aisha Patel',
    lastActivity: 'Lost to competitor — budget constraints',
    probability: 0,
    daysInStage: 0,
    createdAt: '2026-05-15T10:00:00Z',
  },
  {
    id: 'deal-10',
    company: 'Massive Dynamic',
    contact: 'Nina Sharp',
    stage: 'proposal',
    value: 320000,
    repName: 'Marcus Johnson',
    lastActivity: 'Enterprise pricing approved by VP',
    probability: 65,
    daysInStage: 10,
    createdAt: '2026-05-18T14:00:00Z',
  },
  {
    id: 'deal-11',
    company: 'Tyrell Corporation',
    contact: 'Eldon Tyrell',
    stage: 'closed-lost',
    value: 92000,
    repName: 'Sarah Chen',
    lastActivity: 'Budget freeze — timing not right for Q2 rollout',
    probability: 0,
    daysInStage: 0,
    createdAt: '2026-05-12T09:00:00Z',
  },
  {
    id: 'deal-12',
    company: 'Umbrella Corp',
    contact: 'Albert Wesker',
    stage: 'closed-lost',
    value: 145000,
    repName: 'David Park',
    lastActivity: 'Failed security audit — needs FedRAMP authorization',
    probability: 0,
    daysInStage: 0,
    createdAt: '2026-05-10T11:00:00Z',
  },
  {
    id: 'deal-13',
    company: 'Black Mesa',
    contact: 'Gordon Freeman',
    stage: 'closed-lost',
    value: 68000,
    repName: 'Aisha Patel',
    lastActivity: 'Lost to competitor — pricing undercut by 35%',
    probability: 0,
    daysInStage: 0,
    createdAt: '2026-05-08T14:00:00Z',
  },
  {
    id: 'deal-14',
    company: 'Aperture Science',
    contact: 'Cave Johnson',
    stage: 'closed-lost',
    value: 210000,
    repName: 'Marcus Johnson',
    lastActivity: 'CFO rejected — budget reallocated to infrastructure',
    probability: 0,
    daysInStage: 0,
    createdAt: '2026-05-05T10:00:00Z',
  },
]
