export { mockCalls, objectionCategories, type CallAnalysis, type ObjectionCategory } from './calls'
export { mockDeals, pipelineStages, type Deal } from './deals'
export { mockReps, type RepScorecard } from './reps'
export { mockBenchmarks, teamMetrics, type BenchmarkSegment } from './benchmarks'
export { mockFollowUps, type FollowUp } from './followups'
export { mockBriefs, type PreCallBrief } from './briefs'
